# Generated by Django 3.2.7 on 2021-11-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_result_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.PositiveIntegerField(null=True)),
                ('b', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
